### PR TITLE
test create post

### PR DESCRIPTION
**Pull request by stefaniebutland**
Create draft PR of Beth Duckles comm call post. 

Didn't work until Julie added me as collaborator on this repo.
For the record error msg was:
```
> pr_push()
Error: Internal error: Unexpected GitHub remote configuration: 'theirs'
```

### CODE REVIEW

**Comment by jules32** [comment]
Hi Stef! Some beginning sleuthing, this is the home page: 
image

**Comment by stefaniebutland** [comment]
(no checking needed from you rn Julie)
Clicking on [this preview](https://deploy-preview-24--hardcore-borg-58bfb4.netlify.app/) (bottom one on list) home page looks fine. Note there are 10 netlify checks: 1-5 fail and 6-10 pass. Seems like these are 2 sets of similar tests. 

Screen Shot 2022-04-23 at 9 59 42 AM

**Comment by stefaniebutland** [comment]
Pushed more commits (to test adding image). Post still does not appear in preview or when I explicitly point to post preview url https://deploy-preview-24--hardcore-borg-58bfb4.netlify.app/blog/2022/04/26/beth-duckles.md.

Will need help troubleshooting. 

Error msg in [netlify deploy log](https://app.netlify.com/sites/sad-williams-fa509f/deploys/6265c8b5c36a7f00080afef4) when I click `Header rules - sad-williams-fa509f Failing after 17s — Deploy failed`
```
3:02:01 PM: Failing build: Failed to parse configuration
3:02:01 PM: Failed during stage 'Reading and parsing configuration files': 
When resolving config file /opt/build/repo/netlify.toml:
Base directory does not exist: /opt/build/repo/https:/github.com/openscapes/website

: exit status 1
```

**Comment by stefaniebutland** [comment]
I've incorporated Beth's edits and PR is ready for you to check and advise me on or make fixes.

Notes
- post preview: https://deploy-preview-24--hardcore-borg-58bfb4.netlify.app/blog/2022/04/26/beth-duckles/ (can't get to it by clicking blog listing)
- img of QDA slide does not appear in preview
- banner img (YAML `banner: img/blog/beth-duckles-what-is-qda.png`) does not appear on [blog list page preview](https://deploy-preview-24--hardcore-borg-58bfb4.netlify.app/blog/). Does banner img have to be square?

**Review by jules32 — APPROVED** [review]

**Pull request merged**
