### PR TITLE
AFSC post

### PR DESCRIPTION
**Pull request by stefaniebutland**

### CODE REVIEW

**Comment by stefaniebutland** [comment]
@jules32 I'd appreciate your review. The bulk of post is verbatim from the report doc. I drafted title, preface and conclusion which echoes theirs. I think we can publish then I'll share with Em et al before tweeting. Tweet Friday morning most likely

**Review by jules32 — COMMENTED** [review]
thanks @stefaniebutland this looks great!

**Comment by stefaniebutland** [comment]
I'll fix some formatting this morning

**Comment by jules32** [comment]
Thanks Stef!

**Pull request merged**
